In [ ]:
"""
import numpy as np
a = np.array([x,y...])
a = np.array([[x,b...],[c,d...] ... ])
a.ndim
a[0]
a.itemsize - size of each element in bytes
a.dtype - data type of array
a = np.array([[x,b...],[c,d...] ... ], dtype = float/'float'/np.float64/int64/complex)
np.arange(start, end) returns an array instead of list else same as range()
np.arange(end) return [0,1,2,..., end]
np.arange(start,end,step)
np.zeros((sizeofx, sizeofy))
np.ones((sizeofx, sizeofy))
a.shape
a.reshape((sizeofx, sizeofy))
a.ravel() flatten the array.
a.min()
a.max()
a.sum() # default is columns
a.sum(axis = 1) here rows.
np.sqrt(a)
np.std(a)
a + b
a * b
a - b
a / b
a.dot(b)
"""

In [2]:
import numpy as np

In [7]:
a = np.array([5,6,9])

In [8]:
a.ndim

1

In [9]:
a[0]

5

In [10]:
a[1]

6

In [11]:
a = np.array([[1,2],[3,4],[5,6]])

In [12]:
a.ndim

2

In [13]:
a 

array([[1, 2],
       [3, 4],
       [5, 6]])

In [14]:
a.itemsize

4

In [15]:
a.dtype

dtype('int32')

In [3]:
a = np.array([[1,2],[3,4],[5,6]], dtype = 'float')

In [19]:
a = np.array([[1,2],[3,4],[5,6]], dtype = np.float64)

In [20]:
a.dtype

dtype('float64')

In [21]:
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [22]:
a.itemsize

8

In [23]:
a.size

6

In [24]:
a.shape

(3, 2)

In [25]:
a = np.array([[1,2],[3,4],[5,6]], dtype = complex)

In [26]:
a

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

In [27]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [28]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [29]:
l = range(5)

In [30]:
l

range(0, 5)

In [31]:
l[0]

0

In [32]:
np.arange(1,5)

array([1, 2, 3, 4])

In [5]:
np.arange(3)

array([0, 1, 2])

In [34]:
np.arange(1, 5, 2)

array([1, 3])

In [35]:
np.linspace(1,5,10) # linearly spaced.

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [37]:
a = np.array([[1,2],[3,4],[5,6]], dtype = int)

In [38]:
a.dtype

dtype('int32')

In [39]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [40]:
a.shape

(3, 2)

In [41]:
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
a.ravel() # flatten the array.

array([1, 2, 3, 4, 5, 6])

In [44]:
# Note none of the above functions will later the original array.

In [45]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [46]:
a.min()


1

In [47]:
a.max()

6

In [48]:
a.sum()

21

In [51]:
# Concept of axis.
# axis 0 means columns
# axis 1 means rows.
a.sum(axis = 0) # ([1 + 3 + 5, 2 + 4 + 6])

array([ 9, 12])

In [52]:
a.sum(axis = 1)

array([ 3,  7, 11])

In [53]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [54]:
np.std(a)

1.707825127659933

In [57]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

In [58]:
a

array([[1, 2],
       [3, 4]])

In [60]:
b

array([[5, 6],
       [7, 8]])

In [61]:
a + b

array([[ 6,  8],
       [10, 12]])

In [62]:
a * b

array([[ 5, 12],
       [21, 32]])

In [63]:
a / b

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [64]:
a.dot(b)

array([[19, 22],
       [43, 50]])