In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn import linear_model

In [4]:
df = pd.read_csv("house_price_monore.csv")
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [9]:
# preprocessing. 
import math
median_bedrooms = math.floor(df.bedrooms.median())
median_bedrooms

4

In [11]:
df.bedrooms = df.bedrooms.fillna(median_bedrooms)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [12]:
reg = linear_model.LinearRegression()
reg.fit(df[['area', 'bedrooms', 'age']], df[['price']])

LinearRegression()

In [14]:
reg.predict([[3000,5,1]])

C:\Users\sri\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[671223.01017287]])

In [17]:
reg.coef_

array([[  112.06244194, 23388.88007794, -3231.71790863]])

In [18]:
reg.intercept_

array([221323.0018654])

In [19]:
# exercise - hiring.csv

In [31]:
import pandas as pd
import numpy as np
from sklearn import linear_model 

In [32]:
df = DataFrame({
    'experience': [,,'five', 'two', 'seven', 'three', 'ten', 'eleven']
})
df

SyntaxError: invalid syntax (4282098601.py, line 2)

In [33]:
df = pd.read_csv("hiring.csv")
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [34]:
df_new = df.replace({
    'five': 5,
    'two': 2,
    'seven': 7,
    'three': 3,
    'ten': 10,
    'eleven': 11,    
})
df_new

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0         NaN                    8.0                           9      50000
1         NaN                    8.0                           6      45000
2         5.0                    6.0                           7      60000
3         2.0                   10.0                          10      65000
4         7.0                    9.0                           6      70000
5         3.0                    7.0                          10      62000
6        10.0                    NaN                           7      72000
7        11.0                    7.0                           8      80000

In [35]:
import math
experience_median = math.floor(df_new['experience'].median())
experience_median

6

In [36]:
df_new.experience = df_new['experience'].fillna(experience_median)
df_new

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0         6.0                    8.0                           9      50000
1         6.0                    8.0                           6      45000
2         5.0                    6.0                           7      60000
3         2.0                   10.0                          10      65000
4         7.0                    9.0                           6      70000
5         3.0                    7.0                          10      62000
6        10.0                    NaN                           7      72000
7        11.0                    7.0                           8      80000

In [37]:
test_score_median = math.floor(df_new['test_score(out of 10)'].median())
test_score_median

8

In [38]:
df_new['test_score(out of 10)'] = df_new['test_score(out of 10)'].fillna(experience_median)
df_new

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0         6.0                    8.0                           9      50000
1         6.0                    8.0                           6      45000
2         5.0                    6.0                           7      60000
3         2.0                   10.0                          10      65000
4         7.0                    9.0                           6      70000
5         3.0                    7.0                          10      62000
6        10.0                    6.0                           7      72000
7        11.0                    7.0                           8      80000

In [39]:
# now regression. 

In [42]:
reg = linear_model.LinearRegression()
reg.fit(df_new[['experience', 'test_score(out of 10)', 'interview_score(out of 10)']], df_new[['salary($)']])


LinearRegression()

In [43]:
reg.predict([[2,9,6], [12,10,10]])

C:\Users\sri\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[46516.32225217],
       [88211.44055106]])

In [44]:
reg.coef_

array([[2891.88379754,  973.9442947 , 2950.58400719]])

In [45]:
reg.intercept_

array([14263.55196167])